# Generated by Django 4.1.4 on 2023-02-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paycheck',
            name='OTPayRate',
        ),
        migrations.RemoveField(
            model_name='paycheck',
            name='payRate',
        ),
    ]
