# Generated by Django 4.1.4 on 2023-02-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0002_remove_paycheck_otpayrate_remove_paycheck_payrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='OTPayRate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='payRate',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
        ),
    ]
