# Generated by Django 4.1.7 on 2023-02-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychecks', '0003_paycheck_otpayrate_paycheck_payrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='cutOffDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
