# Generated by Django 4.1.4 on 2023-01-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='numberOfEmployees',
        ),
    ]
