# Generated by Django 4.1.4 on 2023-01-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockIn', models.DecimalField(decimal_places=2, max_digits=8)),
                ('clockOut', models.DecimalField(decimal_places=2, max_digits=8)),
                ('startLunch', models.DecimalField(decimal_places=2, max_digits=8)),
                ('returnLunch', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
