# Generated by Django 4.1.4 on 2023-01-03 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
        ('clock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clock',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.shift'),
        ),
    ]
