# Generated by Django 4.1.4 on 2023-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_clock_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clockIn',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockOut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clock',
            name='returnLunch',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clock',
            name='startLunch',
            field=models.TimeField(),
        ),
    ]
