# Generated by Django 4.1.4 on 2023-01-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_alter_clock_clockin_alter_clock_clockout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='clockIn',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clock',
            name='clockOut',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='returnLunch',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='clock',
            name='startLunch',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
