# Generated by Django 4.1.4 on 2023-01-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDate', models.DateField()),
                ('scheduledStart', models.DecimalField(decimal_places=2, max_digits=8)),
                ('scheduledEnd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actualStart', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actualEnd', models.DecimalField(decimal_places=2, max_digits=8)),
                ('isHoliday', models.BooleanField()),
                ('isClockedIn', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
