# Generated by Django 4.1.4 on 2023-01-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='actualEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='actualStart',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='scheduledEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='scheduledStart',
            field=models.TimeField(),
        ),
    ]
