# Generated by Django 4.1.4 on 2023-01-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_shift_actualend_alter_shift_actualstart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='actualEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='actualStart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='scheduledEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='scheduledStart',
            field=models.DateTimeField(),
        ),
    ]
