# Generated by Django 4.1.4 on 2023-02-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_alter_shift_actualend_alter_shift_actualstart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='actualEnd',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='actualStart',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='isClockedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='isHoliday',
            field=models.BooleanField(default=False),
        ),
    ]
