# Generated by Django 4.1.7 on 2023-02-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_alter_shift_actualend_alter_shift_actualstart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='sickTimeUsed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='shift',
            name='vacationTimeUsed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
