# Generated by Django 4.1.7 on 2023-02-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_otpayrate_employee_payrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workDate', models.DateField()),
                ('requestedSickTime', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('requestedVacationTime', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
