# Generated by Django 4.1.7 on 2023-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paidtimeoff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidtimeoff',
            name='ptoRequestStatus',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
