# Generated by Django 4.1.4 on 2023-01-02 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=30)),
                ('jobTitle', models.CharField(max_length=50)),
                ('yearsWithCompany', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer')),
            ],
        ),
    ]
