# Generated by Django 4.1.4 on 2023-01-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='sickTime',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='vacationTime',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=8),
        ),
    ]
