# Generated by Django 4.1.4 on 2023-01-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phoneNumber',
        ),
        migrations.AlterField(
            model_name='employee',
            name='yearsWithCompany',
            field=models.IntegerField(default=0),
        ),
    ]
